#!/bin/bash
set -x
set -e

export RAILS_ENV='production'
export RACK_ENV='production'

[[ ! -s \"$(git rev-parse --git-dir)/shallow\" ]] || git fetch --unshallow
git push git@heroku.com:ahtung-staging.git develop:master
heroku run rake db:migrate --app ahtung-staging
heroku run rake db:seed --app ahtung-staging
# heroku run rake sitemap:refresh --app ahtung-staging
# bundle exec rake smoke:production
